apacheLogs:
  - displayName: "Apache ABC - Server 1 - Production"
    logDirectory: "/opt/apache-tomcat/logs"
    logName: "localhost_access_log.*.txt"
    logPattern: "%{CUSTOMAPACHELOG}"
    hitResponseCodes: [ 200, 202, 305, 304, 400, 401, 402 , 403 , 404, 500 ] #leave null to use default values
    nonPageExtensions: [ ] #leave null to use default values

    metricsFilterForCalculation:
       excludeVisitors: [ ]
       excludeSpiders: [ ]
       excludeUrls: [ ]
       excludeBrowsers: [ ]
       excludeOs: [ ]

    individualMetricsToDisplay:
       includeVisitors: [ ]
       includeSpiders: [ ]
       includePages: [ ".*"]
       includeBrowsers: [ ]
       includeOs: [ ]
       includeResponseCodes: [ 200, 202, 400, 401, 402 , 403 , 404, 500 ]
        
# Number of concurrent threads
noOfThreads: 3

#prefix used to show up metrics in AppDynamics 
metricPrefix: "Custom Metrics|Apache Log Monitor|"